version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: pollution
      POSTGRES_USER: pollution
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_broker
    ports:
      - '1883:1883' # MQTT
      - '8883:8883' # MQTT over TLS
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./certs:/mosquitto/certs # Mount the directory with your TLS certificates
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
  redis_data:
